# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE shortcut;" -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на solomatoff.vyacheslav@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - solomatoff.vyacheslav@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="10138145-3ce7-4a47-9201-f3946d76a3cb"

